import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import WorkPicture1 from "../public/WorkPicture1.jpg";
import WorkPicture2 from "../public/WorkPicture2.jpg";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1 className={styles.title}>Wiza Kaluba</h1>
          <p className={styles.tagline}>I write code that solves problems.</p>
        </div>

        <p className={styles.description}>
          Cloud Native ones. DevOps ones. Embedded ones. Web3 ones. If there's a
          problem, then there won't be.
        </p>
        <Image src={WorkPicture2} alt="Picture of Wiza Kaluba writing code" />

        <div className={styles.grid}>
          <a href="https://github.com/w-kaluba" className={styles.card}>
            <h2>Github &rarr;</h2>
            <p>Look at the problems I've solved recently.</p>
          </a>

          <a
            href="https://uk.linkedin.com/in/wiza-kaluba"
            className={styles.card}
          >
            <h2>LinkedIn &rarr;</h2>
            <p>Look at the people who have given me problems to solve.</p>
          </a>

          <a
            href="https://medium.com/@wizakaluba"
            className={styles.card}
          >
            <h2>Blog &rarr;</h2>
            <p>Read about how I solve problems.</p>
          </a>

          <a href="/contactme" className={styles.card}>
            <h2>Contact Me &rarr;</h2>
            <p>Give me a problem to solve.</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
