import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Wiza Kaluba
        </h1>
        <p className={styles.tagline}>I write code that solves problems.</p>

        <p className={styles.description}>
          Cloud Native ones. DevOps ones. Embedded ones. Web3 ones. If there's a problem, I'll probably try and solve it.
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/w-kaluba" className={styles.card}>
            <h2>Github &rarr;</h2>
            <p>Look at the problems I've solved recently.</p>
          </a>

          <a href="wizhttps://uk.linkedin.com/in/wiza-kaluba" className={styles.card}>
            <h2>LinkedIn &rarr;</h2>
            <p>Look at the people who have given me problems to solve.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Blog &rarr;</h2>
            <p>Read about how I solve problems.</p>
          </a>

          <a
            href="/contactme"
            className={styles.card}
          >
            <h2>Contact Me &rarr;</h2>W
            <p>
              Give me a problem to solve.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
